### ISSUE TITLE
Warning about unmatched double quotes when restoring

### ISSUE THREAD

**Issue by oliverklee** [gkiefer/backup2l#5] opened 2016-08-06 12:26 UTC
This happens using backup2l 1.5-8 from Kubuntu Xenial using the DRIVER_TAR_GZ_SPLIT driver:

klee@gonzales:/opt/restored$ sudo backup2l -r /  
backup2l v1.5 by Gundolf Kiefer

Active files in <all.1011>: 368591
  found in all.1011:    4613   (363978 left)
  found in all.101:    41730   (322248 left)
  found in all.1:      322248   (    0 left)

Restoring 80513 directories...
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
Restoring files...

**Comment by gkiefer** [comment] 2017-03-17 12:44
Closing this as a duplicate of https://github.com/gkiefer/backup2l/issues/4 .

**Closed as completed by gkiefer** 2017-03-17 12:44 UTC
