### ISSUE TITLE
tar: --no-recursion has no effect

### ISSUE THREAD

**Issue by zounp** [gkiefer/backup2l#22] opened 2021-06-08 11:40 UTC
Thanks for backup2l I like it a lot.

backup2l shows:
Creating archive using 'DRIVER_TAR_BZ2'...
  tar: The following options were used after any non-optional arguments in archive create or update mode.  These options are positional and affect only arguments that follow
+them.  Please, rearrange them properly.
  tar: --no-recursion has no effect
  tar: Exiting with failure status due to previous errors

Everything seems to work fine.
What to do?

**Comment by gkiefer** [comment] 2021-06-25 12:12
This is probably a duplicate of #16 (and #18) and has been fixed in HEAD.

If not, please re-open #16 and provide some more information (backup2l version, tar version).

Thanks for reporting and helping to improve the tool!

**Closed as completed by gkiefer** 2021-06-25 12:12 UTC

**Comment by zounp** [comment] 2021-06-26 10:42
I changed the code in /usr/bin/backup2l (version 1.6 on Debian 10. tar version 1.30) manually after reading #16. For

DRIVER_TAR () to:  tar cf $3 --no-recursion -T $4 --numeric-owner 2>&1 \
DRIVER_TAR_GZ () to:  tar czf $3 --no-recursion -T $4 2>&1 \ 
DRIVER_TAR_BZ2 () to:  tar cjf $3 --no-recursion -T $4 2>&1 \

What is HEAD?

**Comment by gkiefer** [comment] 2021-06-30 11:16
"HEAD" was meant to refer to the latest version in Git.
