### ISSUE TITLE
Cannot backup/restore file with brackets in the file name

### ISSUE THREAD

**Issue by oliverklee** [gkiefer/backup2l#4] opened 2016-08-06 12:26 UTC
This happens using backup2l 1.5-8 from Kubuntu Xenial using the DRIVER_TAR_GZ_SPLIT driver:

klee@gonzales:/opt/restored$ sudo backup2l -r /  
backup2l v1.5 by Gundolf Kiefer

Active files in <all.1011>: 368591
  found in all.1011:    4613   (363978 left)
  found in all.101:    41730   (322248 left)
  found in all.1:      322248   (    0 left)

Restoring 80513 directories...
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
Restoring files...
  all.1011.tgz_split: 4613 file(s) using 'DRIVER_TAR_GZ_SPLIT'
  all.101.tgz_split: 41730 file(s) using 'DRIVER_TAR_GZ_SPLIT'
    tar: home/klee/.dropbox/command_socket: Not found in archive
    tar: home/klee/.dropbox/iface_socket: Not found in archive
    tar: home/klee/.thunderbird/axbuu1ii.default/ImapMail/imap.gmail.com/\[Gmail\].sbd/All Mail: Not found in archive
    tar: home/klee/.thunderbird/axbuu1ii.default/ImapMail/imap.gmail.com/\[Gmail\].sbd/Important: Not found in archive
    tar: home/klee/.thunderbird/axbuu1ii.default/ImapMail/imap.gmail.com/\[Gmail\].sbd/Starred: Not found in archive
    tar: Exiting with failure status due to previous errors

**Comment by gkiefer** [comment] 2017-03-17 12:43
Another log example is shown at: https://github.com/gkiefer/backup2l/issues/5

**Comment by boppy** [comment] 2018-09-24 08:41
see my fix proposal in #12

**Comment by gkiefer** [comment] 2018-11-10 20:07
Closing as a duplicate of #12

**Closed as completed by gkiefer** 2018-11-10 20:07 UTC
